"""add fields in otp model./

Revision ID: 1c55ee3eb836
Revises: 83e64c77bda5
Create Date: 2026-09-22 17:20:27.414327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c55ee3eb836'
down_revision: Union[str, Sequence[str], None] = '83e64c77bda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=258), nullable=False))
    op.add_column('otp', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.add_column('otp', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_otp_username'), 'otp', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_username'), table_name='otp')
    op.drop_column('otp', 'password')
    op.drop_column('otp', 'username')
    op.drop_column('otp', 'full_name')
    # ### end Alembic commands ###
